name: Publish
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: lmd-linux/publish-debuild@v1
        with:
          repo: ${{ github.repository }}
          ssh_key: ${{ secrets.SSH_KEY }}
